-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 18:10:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_cliente` (
  `cliente_id` INT NOT NULL,
  `cliente_razon_social` VARCHAR(255) NOT NULL,
  `cliente_ruc` VARCHAR(45) NOT NULL,
  `cliente_establecimiento` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_factura` (
  `factura_id` INT NOT NULL AUTO_INCREMENT,
  `factura_serie` VARCHAR(45) NOT NULL,
  `factura_nro` VARCHAR(45) NOT NULL,
  `factura_fecha_emision` DATE NOT NULL,
  `factura_tipo_moneda` DOUBLE NOT NULL,
  `factura_observacion` VARCHAR(45) NOT NULL,
  `factura_subtotal` DOUBLE NOT NULL,
  `factura_igv` DOUBLE NOT NULL,
  `factura_total` DOUBLE NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`factura_id`),
  CONSTRAINT `fk_tbl_factura_tbl_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`tbl_cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_producto` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `producto_nombre` VARCHAR(255) NOT NULL,
  `producto_precio` DOUBLE NOT NULL,
  PRIMARY KEY (`producto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_factura_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_factura_producto` (
  `factura_producto_id` INT NOT NULL AUTO_INCREMENT,
  `factura_producto_cantidad` INT NOT NULL,
  `factura_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`factura_producto_id`),
  CONSTRAINT `fk_tbl_factura_productos_tbl_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `mydb`.`tbl_factura` (`factura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_productos_tbl_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`tbl_producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
